GET http://localhost:5000/contacts

###
GET http://localhost:5000/contacts/2

###
POST http://localhost:5000/contacts
Content-Type: application/json

{

    "nome": "teste api",
    "apelido": "teste",
    "email": "teste@teste.com",
    "telefone": "16 99999-1111"
  }

###
PUT http://localhost:5000/contacts/2
Content-Type: application/json

{
    "active": 0,
    "apelido": "teste-2",
    "email": "teste2@teste.com",
    "nome": "teste-2 api",
    "telefone": "16 99999-2222"
}


###
DELETE  http://localhost:5000/contacts/3