GET http://localhost:5000/roles

###
GET http://localhost:5000/roles/2

###
POST http://localhost:5000/roles
Content-Type: application/json

{
  "role": "ADMIN"
}

###
PUT http://localhost:5000/roles/1
Content-Type: application/json

{
  "role": "ADMINISTRATO"
}

###
DELETE  http://localhost:5000/roles/2